---
output:
    pdf_document:
    latex_engine: xelatex
html_document:
    df_print: paged
toc: yes
theme: united
editor_options:
    markdown:
    wrap: sentence
intent: yes
link-citations: yes
linestretch: 1.25
indent: yes
fontsize: 11pt
csl: associacao-brasileira-de-normas-tecnicas-eceme.csl
---


# 6. Conclusão

|      Desenvolvemos no projeto a primeira modelagem de distribuição potencial para as espécies *Lonchophylla bokermanni* Sazima e colab. e *Encholirium subsecundum* (Baker) Mez, tanto para o presente quanto para cenários futuros. Os resultados mostraram que pode acontecer o *mismatch* espacial no futuro com relação à distribuição do morcego, enquanto que a planta não apresentou *mismatch* com o morcego no modelos futuros. Ambas as espécies tiveram alterações agudas no tamanho da área de distribuição potencial nos dois cenários futuros. 

O nosso projeto ressalta a necessidade de estudos que investiguem a interação mutualista entre as duas espécies, como o grau de dependência da interação para ambas. Características como a capacidade de dispersão e dados demográficos são difíceis de serem obtidos, porém são informações valiosas que podem ser utilizadas para a implementação de modelos mais robustos para as duas espécies e que tenham uma capacidade de predição melhor. Compreender como as espécies endêmicas *L. bokermanni* e *E. subsecundum* possuem suas distribuições e interação alteradas pelas mudanças climáticas pode ser questão chave não apenas para a tomada de decisão e políticas quanto à sua conservação, mas também para entender como sistemas planta-polinizador com espécies raras e de distribuição restrita podem ser afetados em cenários climáticos futuros.



