---
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
    toc: yes
    theme: united
editor_options:
  markdown:
    wrap: sentence
intent: yes
link-citations: yes
linestretch: 1.25
indent: yes
fontsize: 11pt
csl: associacao-brasileira-de-normas-tecnicas-eceme.csl
---


# 1. Introdução



As mudanças climáticas, especialmente o aumento das temperaturas, que ocorrem ao longo de décadas [@IPCC] têm produzido alterações na distribuição geográfica de espécies [@parmesan2003; @parmesan2006] e seus comportamentos [@pecl2017], impactando a maior parte da biodiversidade do planeta. Estudos indicam a tendência de que a redistribuição de espécies esteja acontecendo de maneira acelerada [@pecl2017], comprometendo o funcionamento dos ecossistemas e as interações ecológicas entre os indivíduos, os quais são expostos a condições ambientais incomuns que testam a sensibilidade da comunidade [@williams2009]. 


Diante dessas condições, a migração para nichos climáticos adequados [@parmesan2006] surge como possível resposta de algumas espécies ao cenário climático, o que não ocorre ao mesmo passo nos diferentes grupos de seres vivos, dados diferentes traços funcionais e características ambientais [@doak2010]. Caso a adaptação geográfica das espécies não seja acompanhada também pela adaptação dos outros indivíduos com os quais existem relações ecológicas, ocorre o chamado *mismatch* espacial [@hegland2008; @schweiger2008], que se caracteriza pela diminuição ou ruptura total das interações ecológicas entre as espécies devido à incompatibilidade geográfica das mesmas.  


A fim de investigar como determinadas espécies podem se comportar em cenários climáticos futuros, os Modelos de Distribuição de Espécies (MDEs) são as ferramentas comumente utilizadas para prever as distribuições potenciais de organismos [@elith2009]. Os MDEs são construídos a partir de combinações entre as ocorrências observadas (ou também ausentes) das espécies e as variáveis ambientais preditoras, juntamente com algoritmos de modelagem e métodos matemáticos [@anderson2013; @franklin2010]. A partir dos dados reunidos e das variáveis ambientais estabelecidas, os algoritmos geram os modelos de distribuição das espécies. Esse modelo é então extrapolado para diferentes tempos e áreas geográficas de estudo, visando fazer predições ou descrever padrões [@elith2009]. 



###
No presente trabalho, utilizaremos da Modelagem de Distribuição para prever a distribuição potencial futura da espécie de vegetal *Encholirium subsecundum* (Baker) Mez e de seu único polinizador conhecido \cite{DIAS, VOGEL}, o quiróptero *Lonchophylla bokermanni* Sazima *et al.*, 1978, projetando dois cenários de mudanças climáticas, pessimista e otimista. A partir dos modelos gerados, os mapas de distribuição  resultante de ambas as espécies serão sobrepostos com o intuito de observar se ocorre *mismatch* espacial entre as espécies.


*Mimosa lewisii* é uma espécie vegetal arbustiva endêmica do Brasil, mais precisamente dos biomas da Caatinga e Mata Atlântica, com registros em estados do nordeste como Bahia e Pernambuco \cite{FLORA}. O único polinizador registrado da espécie é o morcego *Lonchophylla mordax* \cite{DIAS, VOGEL}.O gênero \textit{Mimosa} é tido como ameaçado \cite{MARTINELLI}, em virtude da distribuição restrita das espécies. 


\textit{Lonchophylla mordax} \cite{MORDAX} é uma espécie de quiróptero também endêmica do Brasil, com ocorrências no bioma da Amazônia na região Norte do Brasil, Caatinga e Cerrado no Nordeste do país e Mata Atlântica na região Sudeste \cite{MORATELLI}. Sua dieta é principalmente nectarívora, mas também pode se alimentar de frutas e insetos. \textit{L. mordax} é classificado como quase ameaçado \cite{LIM}, tendo em vista a degradação de seus habitats. 
###