---
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
    toc: yes
    theme: united
editor_options:
  markdown:
    wrap: sentence
intent: yes
link-citations: yes
linestretch: 1.25
indent: yes
fontsize: 11pt
csl: associacao-brasileira-de-normas-tecnicas-eceme.csl
---

\clearpage

# Resultados

|     O algoritmo Maxent demonstrou boa performance preditiva, obtendo altos valores médios de AUC ([gráficos 8 e 9](#apêndice)). A proporção de área potencial ganha e perdida sob os diferentes cenários climáticos com relação ao presente variou entre ambas as espécies (\label{tabela6}), todas apresentaram contração na área ambiental adequada nos cenários futuros de mudanças climáticas. 


Os modelos previram redução de 36.98% de áreas adequadas (com respeito à área presente) para *Lonchophylla bokermanni* no cenário de RCP 4.5 para o ano de 2050 e diminuição de 58.06% de área para o panorama de RCP 8.5, para 2050 ([tabela 7](#apêndice)). A mesma tendência foi observada para *Encholirium subsecundum*, a qual previmos encolhimento de 72.70% de área apropriada (relativa à área do presente) para o futuro de RCP 4.5 (2050), enquanto que no cenário de RCP 8.5 a redução na área é de 81.11% (com respeito ao presente).


Previmos uma diminuição na área de sobreposição potencial entre a distribuição de ambas as espécies (planta+morcego), a qual diminui 67.76% no cenário de RCP 4.5 e 79.86% no RCP 8.5, em relação à sobreposição no presente ([tabela 8](#apêndice)). A taxa de *mismatch* espacial (desencontro geográfico) entre a planta e o morcego aumentou com relação à distribuição de *Lonchophylla bokermanni*, que apresentou 26.07% de sua distribuição potencial presente sem sobreposição com a da planta, no cenário de RCP 4.5, 61.56% da área do morcego não apresentou sobreposição e no RCP 8.5, 63.07% de sua área. Em contrapartida, observamos diminuição na taxa de *mismatch* para a planta, previmos 28.06% de sua área presente não tenha sobreposiçãp com a distribuição do morcego, 15.07% da área no futuro RCP 4.5 sem sobreposição e 23.30% da área no RCP 8.5 ([tabela 9](#apêndice)). 









